#include "template_picker.h"

#include <cstdio>
#include <imgui.h>

namespace magnetar {

// ─── 8 Shadertoy-compatible shader templates ─────────────────────────────────

static const char* kBlankSource =
    "void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
    "{\n"
    "    fragColor = vec4(0.0, 0.0, 0.0, 1.0);\n"
    "}\n";

static const char* kGradientSource =
    "void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
    "{\n"
    "    vec2 uv = fragCoord / iResolution.xy;\n"
    "\n"
    "    // Animated color cycling\n"
    "    vec3 col = 0.5 + 0.5 * cos(iTime + uv.xyx + vec3(0.0, 2.0, 4.0));\n"
    "\n"
    "    // Subtle wave pattern\n"
    "    float wave = 0.5 + 0.5 * sin(uv.x * 6.2831 + iTime * 1.5)\n"
    "                     * sin(uv.y * 6.2831 + iTime * 0.7);\n"
    "    col = mix(col, col * (0.8 + 0.4 * wave), 0.3);\n"
    "\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static const char* kPlasmaSource =
    "void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
    "{\n"
    "    vec2 uv = fragCoord / iResolution.xy;\n"
    "    float t = iTime;\n"
    "\n"
    "    float v1 = sin(uv.x * 10.0 + t);\n"
    "    float v2 = sin(10.0 * (uv.x * sin(t / 2.0) + uv.y * cos(t / 3.0)) + t);\n"
    "    float cx = uv.x + 0.5 * sin(t / 5.0);\n"
    "    float cy = uv.y + 0.5 * cos(t / 3.0);\n"
    "    float v3 = sin(sqrt(100.0 * (cx * cx + cy * cy) + 1.0) + t);\n"
    "    float v = v1 + v2 + v3;\n"
    "\n"
    "    vec3 col = vec3(\n"
    "        sin(v * 3.14159) * 0.5 + 0.5,\n"
    "        sin(v * 3.14159 + 2.094) * 0.5 + 0.5,\n"
    "        sin(v * 3.14159 + 4.188) * 0.5 + 0.5\n"
    "    );\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static const char* kCosmicTunnelSource =
    "void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
    "{\n"
    "    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;\n"
    "    float angle = atan(uv.y, uv.x);\n"
    "    float radius = length(uv);\n"
    "\n"
    "    float tunnel = 1.0 / (radius + 0.001);\n"
    "    float texX = angle / 3.14159 + iTime * 0.1;\n"
    "    float texY = tunnel + iTime * 0.5;\n"
    "\n"
    "    vec3 col = vec3(\n"
    "        0.5 + 0.5 * sin(texX * 8.0 + texY * 4.0),\n"
    "        0.5 + 0.5 * sin(texX * 6.0 + texY * 3.0 + 2.0),\n"
    "        0.5 + 0.5 * sin(texX * 4.0 + texY * 5.0 + 4.0)\n"
    "    );\n"
    "    col *= smoothstep(0.0, 0.5, radius) * (1.0 - smoothstep(0.5, 2.0, radius));\n"
    "    col *= tunnel * 0.3;\n"
    "\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static const char* kRaymarchingSphereSource =
    "float sdSphere(vec3 p, float r) { return length(p) - r; }\n"
    "\n"
    "float scene(vec3 p) {\n"
    "    return sdSphere(p, 1.0);\n"
    "}\n"
    "\n"
    "vec3 getNormal(vec3 p) {\n"
    "    vec2 e = vec2(0.001, 0.0);\n"
    "    return normalize(vec3(\n"
    "        scene(p + e.xyy) - scene(p - e.xyy),\n"
    "        scene(p + e.yxy) - scene(p - e.yxy),\n"
    "        scene(p + e.yyx) - scene(p - e.yyx)\n"
    "    ));\n"
    "}\n"
    "\n"
    "void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
    "{\n"
    "    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;\n"
    "    vec3 ro = vec3(0.0, 0.0, -3.0);\n"
    "    vec3 rd = normalize(vec3(uv, 1.0));\n"
    "\n"
    "    float t = 0.0;\n"
    "    for (int i = 0; i < 64; i++) {\n"
    "        vec3 p = ro + rd * t;\n"
    "        float d = scene(p);\n"
    "        if (d < 0.001) break;\n"
    "        t += d;\n"
    "        if (t > 20.0) break;\n"
    "    }\n"
    "\n"
    "    vec3 col = vec3(0.02, 0.02, 0.04);\n"
    "    if (t < 20.0) {\n"
    "        vec3 p = ro + rd * t;\n"
    "        vec3 n = getNormal(p);\n"
    "        vec3 lightDir = normalize(vec3(sin(iTime), 0.8, cos(iTime)));\n"
    "        float diff = max(dot(n, lightDir), 0.0);\n"
    "        float spec = pow(max(dot(reflect(-lightDir, n), -rd), 0.0), 32.0);\n"
    "        col = vec3(0.2, 0.5, 0.8) * diff + vec3(1.0) * spec * 0.5 + vec3(0.05);\n"
    "    }\n"
    "\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static const char* kMandelbrotSource =
    "void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
    "{\n"
    "    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;\n"
    "\n"
    "    // Zoom into an interesting region over time\n"
    "    float zoom = pow(1.5, mod(iTime * 0.5, 12.0));\n"
    "    vec2 center = vec2(-0.745, 0.186);\n"
    "    vec2 c = center + uv / zoom;\n"
    "\n"
    "    vec2 z = vec2(0.0);\n"
    "    int maxIter = 128;\n"
    "    int iter = 0;\n"
    "    for (int i = 0; i < 128; i++) {\n"
    "        z = vec2(z.x * z.x - z.y * z.y, 2.0 * z.x * z.y) + c;\n"
    "        if (dot(z, z) > 4.0) break;\n"
    "        iter++;\n"
    "    }\n"
    "\n"
    "    float t = float(iter) / float(maxIter);\n"
    "    vec3 col = 0.5 + 0.5 * cos(3.0 + t * 6.2831 * 2.0 + vec3(0.0, 0.6, 1.0));\n"
    "    if (iter == maxIter) col = vec3(0.0);\n"
    "\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static const char* kWaterRipplesSource =
    "void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
    "{\n"
    "    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;\n"
    "    float r = length(uv);\n"
    "\n"
    "    // Concentric ripples expanding outward\n"
    "    float wave1 = sin(r * 30.0 - iTime * 4.0) * exp(-r * 3.0);\n"
    "    float wave2 = sin(r * 20.0 - iTime * 3.0 + 1.5) * exp(-r * 2.0);\n"
    "    float wave = (wave1 + wave2) * 0.5;\n"
    "\n"
    "    // Distort UV for a refraction-like effect\n"
    "    vec2 distort = uv * wave * 0.1;\n"
    "    vec2 texUV = fragCoord / iResolution.xy + distort;\n"
    "\n"
    "    // Water color gradient\n"
    "    vec3 deepBlue = vec3(0.0, 0.05, 0.15);\n"
    "    vec3 lightBlue = vec3(0.1, 0.4, 0.7);\n"
    "    vec3 col = mix(deepBlue, lightBlue, 0.5 + wave * 0.8);\n"
    "\n"
    "    // Specular highlight\n"
    "    float spec = pow(max(wave, 0.0), 4.0) * 0.6;\n"
    "    col += vec3(spec);\n"
    "\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static const char* kMagnetarLogoSource =
    "// Magnetar Logo - Cel-shaded neutron star with accretion ring\n"
    "// Ported from the project's official logo shader\n"
    "\n"
    "// CI PALETTE\n"
    "vec3 CI_VIOLET  = vec3(0.545, 0.361, 0.965);\n"
    "vec3 CI_CYAN    = vec3(0.024, 0.714, 0.831);\n"
    "vec3 CI_MAGENTA = vec3(0.851, 0.275, 0.937);\n"
    "vec3 CI_NOVA    = vec3(0.976, 0.451, 0.086);\n"
    "vec3 VOID_BG    = vec3(0.039, 0.039, 0.059);\n"
    "vec3 INK        = vec3(0.01, 0.01, 0.02);\n"
    "\n"
    "float hash21(vec2 p){\n"
    "    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);\n"
    "}\n"
    "\n"
    "float hash31(vec3 p){\n"
    "    return fract(sin(dot(p, vec3(127.1, 311.7, 74.7))) * 43758.5453);\n"
    "}\n"
    "\n"
    "float nse2(vec2 p){\n"
    "    vec2 i = floor(p);\n"
    "    vec2 f = fract(p);\n"
    "    f = f*f*(3.0-2.0*f);\n"
    "    float a = hash21(i);\n"
    "    float b = hash21(i + vec2(1.0, 0.0));\n"
    "    float c = hash21(i + vec2(0.0, 1.0));\n"
    "    float d = hash21(i + vec2(1.0, 1.0));\n"
    "    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);\n"
    "}\n"
    "\n"
    "float nse3(vec3 p){\n"
    "    vec3 i = floor(p);\n"
    "    vec3 f = fract(p);\n"
    "    f = f*f*(3.0-2.0*f);\n"
    "    float n00 = mix(hash31(i), hash31(i+vec3(1,0,0)), f.x);\n"
    "    float n01 = mix(hash31(i+vec3(0,1,0)), hash31(i+vec3(1,1,0)), f.x);\n"
    "    float n10 = mix(hash31(i+vec3(0,0,1)), hash31(i+vec3(1,0,1)), f.x);\n"
    "    float n11 = mix(hash31(i+vec3(0,1,1)), hash31(i+vec3(1,1,1)), f.x);\n"
    "    return mix(mix(n00, n01, f.y), mix(n10, n11, f.y), f.z);\n"
    "}\n"
    "\n"
    "float fbm2(vec2 p){\n"
    "    float v = 0.0, a = 0.5;\n"
    "    mat2 rot = mat2(0.8, 0.6, -0.6, 0.8);\n"
    "    for(int i=0; i<5; i++){\n"
    "        v += a * nse2(p);\n"
    "        p = rot * p * 2.0;\n"
    "        a *= 0.5;\n"
    "    }\n"
    "    return v;\n"
    "}\n"
    "\n"
    "float fbm3(vec3 p){\n"
    "    float v = 0.0, a = 0.5;\n"
    "    for(int i=0; i<5; i++){\n"
    "        v += a * nse3(p);\n"
    "        p = p * 2.01 + vec3(0.1, 0.2, 0.15);\n"
    "        a *= 0.5;\n"
    "    }\n"
    "    return v;\n"
    "}\n"
    "\n"
    "float celStep(float v, float steps){\n"
    "    return floor(v * steps + 0.5) / steps;\n"
    "}\n"
    "\n"
    "float hatchFn(vec2 px, float density, float angle){\n"
    "    float c = cos(angle), s = sin(angle);\n"
    "    vec2 rotP = vec2(px.x*c - px.y*s, px.x*s + px.y*c);\n"
    "    return smoothstep(0.4, 0.5, abs(fract(rotP.x * density) - 0.5) * 2.0);\n"
    "}\n"
    "\n"
    "float inkLine(float dist, float width, vec2 px, float t){\n"
    "    float wobble = nse2(px * 0.08 + vec2(t * 0.3)) * 0.003;\n"
    "    wobble += nse2(px * 0.2 - vec2(t * 0.15)) * 0.0015;\n"
    "    return 1.0 - smoothstep(0.0, width + wobble, abs(dist));\n"
    "}\n"
    "\n"
    "float surfaceWave(vec3 sp, float t){\n"
    "    float arcs = 0.0;\n"
    "    for(int i = 0; i < 5; i++){\n"
    "        float fi = float(i);\n"
    "        float period = 4.5 + fi * 1.2;\n"
    "        float cycle = mod(t + fi * 1.1, period);\n"
    "        float lifespan = 2.2 + fi * 0.3;\n"
    "        float alive = smoothstep(0.0, 0.15, cycle)\n"
    "                     * (1.0 - smoothstep(lifespan - 0.3, lifespan, cycle));\n"
    "        if(alive < 0.01) continue;\n"
    "        vec3 dir = vec3(0.0);\n"
    "        if(i == 0) dir = normalize(vec3(1.0, 0.4, 0.2));\n"
    "        if(i == 1) dir = normalize(vec3(-0.3, 1.0, 0.5));\n"
    "        if(i == 2) dir = normalize(vec3(0.5, -0.7, 0.8));\n"
    "        if(i == 3) dir = normalize(vec3(-0.8, -0.2, 0.6));\n"
    "        if(i == 4) dir = normalize(vec3(0.2, 0.6, -0.9));\n"
    "        float speed = 1.0 + fi * 0.2;\n"
    "        float frontPos = cycle * speed;\n"
    "        float d = dot(sp, dir);\n"
    "        float distFromFront = d - frontPos + 2.0;\n"
    "        vec3 perpSeed = sp - dir * d;\n"
    "        float jag = 0.0;\n"
    "        jag += nse3(perpSeed * 8.0 + vec3(fi * 5.0)) * 0.5;\n"
    "        jag += nse3(perpSeed * 16.0 + vec3(fi * 11.0)) * 0.25;\n"
    "        jag += nse3(perpSeed * 32.0 + vec3(fi * 17.0)) * 0.12;\n"
    "        distFromFront += jag * 0.8;\n"
    "        float arc = exp(-distFromFront * distFromFront * 300.0);\n"
    "        float crackle = 0.7 + 0.3 * sin(t * 25.0 + fi * 40.0 + d * 30.0);\n"
    "        arc *= crackle;\n"
    "        arcs += arc * alive;\n"
    "    }\n"
    "    return arcs;\n"
    "}\n"
    "\n"
    "void mainImage(out vec4 fragColor, in vec2 fragCoord){\n"
    "    float t = iTime;\n"
    "    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / min(iResolution.x, iResolution.y);\n"
    "    vec2 px = fragCoord;\n"
    "    float r = length(uv);\n"
    "    float angle = atan(uv.y, uv.x);\n"
    "\n"
    "    // Heavy sphere\n"
    "    float sphR = 0.18;\n"
    "    float sphereDist = r - sphR;\n"
    "    float sphereMask = 1.0 - smoothstep(-0.002, 0.002, sphereDist);\n"
    "    vec2 sUV = uv / sphR;\n"
    "    float z2 = 1.0 - dot(sUV, sUV);\n"
    "    float z = sqrt(max(z2, 0.0));\n"
    "    vec3 nrm = vec3(sUV, z);\n"
    "\n"
    "    vec3 ldir = normalize(vec3(-0.3, 0.4, 1.0));\n"
    "    float rawDiff = max(dot(nrm, ldir), 0.0);\n"
    "    float rawSpec = pow(max(dot(reflect(-ldir, nrm), vec3(0,0,1)), 0.0), 16.0);\n"
    "    float diff = celStep(rawDiff, 4.0);\n"
    "    float spec = step(0.5, rawSpec);\n"
    "    float pulse = 1.0 + 0.08*sin(t*2.5) + 0.04*sin(t*6.1) + 0.03*sin(t*11.0);\n"
    "\n"
    "    vec3 sPos = vec3(sUV * 3.0, t * 0.3);\n"
    "    float sNoise = fbm3(sPos * 2.5 + vec3(t*0.2, t*0.15, t*0.1));\n"
    "    float sDetail = fbm3(sPos * 6.0 - vec3(t*0.3, 0.0, t*0.2));\n"
    "    sNoise = celStep(sNoise, 5.0);\n"
    "    sDetail = celStep(sDetail, 4.0);\n"
    "\n"
    "    vec3 sBase = mix(vec3(0.1, 0.05, 0.22), vec3(0.25, 0.14, 0.45), diff);\n"
    "    vec3 plasma = mix(CI_VIOLET * 0.8, CI_CYAN * 0.7, sNoise);\n"
    "    plasma = mix(plasma, CI_MAGENTA * 0.6, sDetail * 0.5);\n"
    "    sBase = mix(sBase, plasma, 0.35 + 0.2 * sNoise);\n"
    "    sBase = mix(sBase, vec3(0.85, 0.9, 1.0), spec * 0.7);\n"
    "\n"
    "    float fresnel = pow(max(1.0 - z, 0.0), 2.5);\n"
    "    float celFresnel = step(0.45, fresnel);\n"
    "    vec3 rimCol = mix(CI_CYAN, CI_VIOLET, 0.5 + 0.5*sin(angle*2.0 + t*0.5));\n"
    "    sBase = mix(sBase, rimCol * 1.4, celFresnel * 0.8 * pulse);\n"
    "\n"
    "    float shadow = 1.0 - diff;\n"
    "    float h1 = hatchFn(px, 0.12, 0.785);\n"
    "    float h2 = hatchFn(px, 0.10, -0.785);\n"
    "    float h3 = hatchFn(px, 0.15, 0.0);\n"
    "    float hatchMask = 0.0;\n"
    "    hatchMask += (1.0-h1) * step(0.4, shadow) * 0.3;\n"
    "    hatchMask += (1.0-h2) * step(0.65, shadow) * 0.25;\n"
    "    hatchMask += (1.0-h3) * step(0.85, shadow) * 0.2;\n"
    "    sBase *= (1.0 - hatchMask * sphereMask);\n"
    "\n"
    "    // Electric arcs\n"
    "    vec3 spherePos3D = vec3(sUV.x, sUV.y, z);\n"
    "    float wavesRaw = surfaceWave(spherePos3D, t) * sphereMask;\n"
    "    float waves = step(0.15, wavesRaw)*0.6 + step(0.4, wavesRaw)*0.4;\n"
    "    vec3 waveCol = mix(CI_CYAN, vec3(1.0, 0.97, 1.0), 0.55) * waves;\n"
    "    sBase += waveCol * 1.2;\n"
    "    float bolts = wavesRaw;\n"
    "\n"
    "    // Saturn-style accretion ring\n"
    "    float tiltAngle = 0.35;\n"
    "    float diskCos = sin(tiltAngle);\n"
    "    float screenTilt = -0.3;\n"
    "    float cst = cos(screenTilt), sst = sin(screenTilt);\n"
    "    vec2 tiltedUV = vec2(uv.x*cst + uv.y*sst, -uv.x*sst + uv.y*cst);\n"
    "    vec2 diskUV = vec2(tiltedUV.x, tiltedUV.y / diskCos);\n"
    "    float diskR = length(diskUV);\n"
    "    float diskAngle = atan(diskUV.y, diskUV.x);\n"
    "    float ringInner = 0.23, ringOuter = 0.40;\n"
    "    float ringMask = smoothstep(ringInner-0.004, ringInner+0.004, diskR)\n"
    "                   * (1.0 - smoothstep(ringOuter-0.004, ringOuter+0.004, diskR));\n"
    "    float bandNoise = nse2(vec2(diskR*40.0, diskAngle*2.0 + t*0.1));\n"
    "    float bands = smoothstep(0.48, 0.52, sin(diskR*70.0)) * 0.25\n"
    "                + smoothstep(0.45, 0.55, sin(diskR*110.0 + 1.5)) * 0.15;\n"
    "    float gapPos = 0.31;\n"
    "    float cassini = 1.0 - exp(-(diskR-gapPos)*(diskR-gapPos)/0.00025);\n"
    "    ringMask *= cassini * (0.55 + 0.45*bandNoise + bands);\n"
    "    ringMask = celStep(ringMask, 5.0);\n"
    "\n"
    "    float ringGrad = smoothstep(ringInner, ringOuter, diskR);\n"
    "    vec3 ringBaseCol = mix(CI_CYAN*0.9, CI_VIOLET*0.7, ringGrad);\n"
    "    ringBaseCol = mix(ringBaseCol, CI_MAGENTA*0.6, bandNoise*0.3);\n"
    "    ringBaseCol = mix(vec3(1.0,0.9,0.95), ringBaseCol, smoothstep(ringInner, ringInner+0.03, diskR));\n"
    "    vec3 ringNrm = normalize(vec3(sin(screenTilt)*0.3, diskCos, cos(screenTilt)*0.8));\n"
    "    float ringDiff = celStep(max(dot(ringNrm, ldir), 0.0), 3.0);\n"
    "    vec3 ringCol = ringBaseCol * (0.55 + 0.45*ringDiff);\n"
    "    float ringShadow = 1.0 - ringDiff;\n"
    "    float ringH1 = hatchFn(px, 0.10, 0.785);\n"
    "    ringCol *= (1.0 - (1.0-ringH1)*step(0.7, ringShadow)*0.15);\n"
    "\n"
    "    float ringInFront = step(tiltedUV.y, 0.0);\n"
    "    float ringBehind = 1.0 - ringInFront;\n"
    "    float sphereOcclude = sphereMask;\n"
    "\n"
    "    // Polar jets\n"
    "    float axA = 0.35;\n"
    "    float jets = 0.0;\n"
    "    for(int i = 0; i < 2; i++){\n"
    "        float dir2 = float(i)*2.0 - 1.0;\n"
    "        vec2 jd = vec2(sin(axA), cos(axA)) * dir2;\n"
    "        float ja = dot(normalize(uv + vec2(0.0001)), jd);\n"
    "        float jb = pow(max(ja, 0.0), 24.0);\n"
    "        float jf = exp(-r*2.0) * smoothstep(sphR, sphR+0.06, r);\n"
    "        float jt = nse2(vec2(r*30.0 - t*3.0, angle*2.0));\n"
    "        jets += jb * jf * (0.4 + 0.6*jt) * 0.7;\n"
    "    }\n"
    "    jets = celStep(jets, 5.0);\n"
    "    vec3 jetCol = mix(CI_VIOLET*0.8, vec3(0.85, 0.75, 1.0), 0.4);\n"
    "\n"
    "    // Outer glow\n"
    "    float halo = exp(-r*2.2)*0.12 * smoothstep(sphR, sphR+0.1, r);\n"
    "    float hN = fbm2(vec2(angle*1.5 + t*0.08, r*4.0));\n"
    "    halo *= (0.6 + 0.6*hN);\n"
    "    halo = celStep(halo, 3.0);\n"
    "    vec3 haloCol = mix(CI_VIOLET*0.3, CI_CYAN*0.3, hN);\n"
    "\n"
    "    // Stars\n"
    "    vec2 stUV = fragCoord / iResolution.xy;\n"
    "    float stf = hash21(floor(stUV * 200.0));\n"
    "    float stars = step(0.9975, stf) * (0.25 + 0.15*sin(t*1.8 + stf*100.0));\n"
    "\n"
    "    // Composite\n"
    "    vec3 col = VOID_BG + vec3(0.02, 0.01, 0.04)*exp(-r*r*4.0);\n"
    "    col += stars * vec3(0.7, 0.8, 1.0);\n"
    "    float totalE = 0.0;\n"
    "    col += haloCol * halo; totalE += halo;\n"
    "    col += jetCol * jets; totalE += jets;\n"
    "    float ringBack = ringMask * ringBehind * (1.0-sphereOcclude);\n"
    "    col += ringCol * ringBack * pulse; totalE += ringBack;\n"
    "    col = mix(col, sBase * pulse, sphereMask); totalE += sphereMask;\n"
    "    float ringFrontVal = ringMask * ringInFront;\n"
    "    col = mix(col, ringCol * pulse, ringFrontVal * 0.95); totalE += ringFrontVal;\n"
    "\n"
    "    // Soft glow\n"
    "    float glowClose = exp(-(r-sphR)*(r-sphR)/0.004)*0.35;\n"
    "    float glowMid   = exp(-(r-sphR)*(r-sphR)/0.015)*0.20;\n"
    "    float glowWide  = exp(-(r-sphR)*(r-sphR)/0.045)*0.10;\n"
    "    float glowUltra = exp(-r*r/0.12)*0.06;\n"
    "    vec3 glowCol = mix(CI_CYAN*0.9, vec3(0.8,0.9,1.0), 0.3)*glowClose\n"
    "                 + mix(CI_VIOLET*0.6, CI_CYAN*0.5, 0.4)*glowMid\n"
    "                 + CI_VIOLET*0.5*glowWide\n"
    "                 + mix(CI_VIOLET*0.3, CI_MAGENTA*0.2, 0.3)*glowUltra;\n"
    "    glowCol *= pulse;\n"
    "    float ringSpill = exp(-(r-0.3)*(r-0.3)/0.02)*0.08;\n"
    "    glowCol += mix(CI_CYAN*0.4, CI_VIOLET*0.3, 0.5)*ringSpill;\n"
    "    float arcGlowSpill = bolts * exp(-(r-sphR)*(r-sphR)/0.008)*0.3;\n"
    "    glowCol += mix(CI_CYAN, vec3(1.0), 0.4)*arcGlowSpill;\n"
    "    col += glowCol * (1.0 - sphereMask*0.7);\n"
    "    totalE += glowClose + glowMid + glowWide;\n"
    "\n"
    "    // Ink outlines\n"
    "    float ink = 0.0;\n"
    "    float ringInFrontMask = ringInFront * ringMask;\n"
    "    float outerLine = inkLine(sphereDist, 0.007, px, t);\n"
    "    float outerLine2 = inkLine(sphereDist+0.002, 0.005, px*1.1, t);\n"
    "    float sphereInk = max(outerLine, outerLine2*0.7);\n"
    "    ink = max(ink, sphereInk*(1.0-ringInFrontMask));\n"
    "    float innerRing = inkLine(sphereDist+0.015, 0.003, px*0.9, t);\n"
    "    ink = max(ink, innerRing*0.5*sphereMask*(1.0-ringInFrontMask));\n"
    "    float specEdge = inkLine(rawSpec-0.5, 0.08, px, t);\n"
    "    ink = max(ink, specEdge*0.35*sphereMask*spec*(1.0-ringInFrontMask));\n"
    "    float be1=inkLine(rawDiff-0.25,0.04,px*1.2,t);\n"
    "    float be2=inkLine(rawDiff-0.50,0.04,px*0.8,t);\n"
    "    float be3=inkLine(rawDiff-0.75,0.04,px*1.05,t);\n"
    "    ink = max(ink, max(max(be1,be2),be3)*0.2*sphereMask*(1.0-ringInFrontMask));\n"
    "\n"
    "    float eA=ringOuter, eB=ringOuter*diskCos;\n"
    "    float ex=tiltedUV.x, ey=tiltedUV.y;\n"
    "    float ep = (ex*ex)/(eA*eA) + (ey*ey)/(eB*eB);\n"
    "    float eDist = (sqrt(ep)-1.0)*eA*0.8;\n"
    "    float ringOutStroke = inkLine(eDist, 0.007, px, t);\n"
    "    float ringOutStroke2 = inkLine(eDist-0.002, 0.005, px*1.1, t);\n"
    "    float ringInk = max(ringOutStroke, ringOutStroke2*0.7);\n"
    "    float ringBehindSphere = ringBehind * sphereMask;\n"
    "    ink = max(ink, ringInk*(1.0-ringBehindSphere));\n"
    "\n"
    "    float arcEdgeLo = step(0.08, wavesRaw);\n"
    "    float arcEdgeHi = step(0.18, wavesRaw);\n"
    "    float arcStroke = arcEdgeLo*(1.0-arcEdgeHi);\n"
    "    ink = max(ink, arcStroke*0.6*sphereMask);\n"
    "\n"
    "    float inkNoise = 0.85 + 0.15*nse2(px*0.05);\n"
    "    col = mix(col, INK, ink*inkNoise);\n"
    "\n"
    "    float grain = nse2(px*0.3 + vec2(t*0.05))*0.04;\n"
    "    col += grain*0.5 - 0.01;\n"
    "    float vig = 1.0 - smoothstep(0.36, 0.5, max(abs(uv.x), abs(uv.y)));\n"
    "    col *= mix(0.5, 1.0, vig);\n"
    "    col = col / (col + vec3(0.9));\n"
    "    col = pow(col, vec3(0.88));\n"
    "    float lum = dot(col, vec3(0.299, 0.587, 0.114));\n"
    "    col = mix(vec3(lum), col, 1.25);\n"
    "\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static const char* kStarfieldSource =
    "// Hash function for pseudo-random values\n"
    "float hash(vec2 p) {\n"
    "    p = fract(p * vec2(123.34, 456.21));\n"
    "    p += dot(p, p + 45.32);\n"
    "    return fract(p.x * p.y);\n"
    "}\n"
    "\n"
    "// Single star layer\n"
    "float starLayer(vec2 uv, float scale, float speed) {\n"
    "    uv *= scale;\n"
    "    uv.y += iTime * speed;\n"
    "    vec2 id = floor(uv);\n"
    "    vec2 gv = fract(uv) - 0.5;\n"
    "\n"
    "    float h = hash(id);\n"
    "    float size = 0.02 + h * 0.03;\n"
    "    float brightness = 0.5 + 0.5 * sin(iTime * (1.0 + h * 3.0) + h * 6.28);\n"
    "    float d = length(gv - (vec2(h, fract(h * 34.0)) - 0.5) * 0.8);\n"
    "    float star = smoothstep(size, size * 0.2, d) * brightness;\n"
    "    return star;\n"
    "}\n"
    "\n"
    "void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
    "{\n"
    "    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;\n"
    "\n"
    "    // Dark background with subtle gradient\n"
    "    vec3 col = vec3(0.01, 0.01, 0.03) + uv.y * 0.02;\n"
    "\n"
    "    // Three parallax layers at different speeds and scales\n"
    "    col += vec3(0.6, 0.7, 1.0) * starLayer(uv, 8.0, 0.05);\n"
    "    col += vec3(0.8, 0.8, 1.0) * starLayer(uv, 16.0, 0.1);\n"
    "    col += vec3(1.0, 0.9, 0.8) * starLayer(uv, 32.0, 0.2);\n"
    "\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static const char* kFeedbackBlurSource =
    "//--- BufferA ---\n"
    "//!channel0 self\n"
    "void mainImage(out vec4 fragColor, in vec2 fragCoord) {\n"
    "    vec2 uv = fragCoord / iResolution.xy;\n"
    "    vec4 prev = texture(iChannel0, uv);\n"
    "    // Slight blur by sampling neighbors\n"
    "    vec2 px = 1.0 / iResolution.xy;\n"
    "    vec4 blur = prev * 0.5\n"
    "        + texture(iChannel0, uv + vec2(px.x, 0.0)) * 0.125\n"
    "        + texture(iChannel0, uv - vec2(px.x, 0.0)) * 0.125\n"
    "        + texture(iChannel0, uv + vec2(0.0, px.y)) * 0.125\n"
    "        + texture(iChannel0, uv - vec2(0.0, px.y)) * 0.125;\n"
    "    // Add a bright moving dot to see accumulation\n"
    "    vec2 center = 0.5 + 0.3 * vec2(cos(iTime), sin(iTime * 0.7));\n"
    "    float d = length(uv - center);\n"
    "    blur += vec4(1.0) * smoothstep(0.02, 0.0, d);\n"
    "    fragColor = blur;\n"
    "}\n"
    "\n"
    "//--- Image ---\n"
    "//!channel0 BufferA\n"
    "void mainImage(out vec4 fragColor, in vec2 fragCoord) {\n"
    "    vec2 uv = fragCoord / iResolution.xy;\n"
    "    fragColor = texture(iChannel0, uv);\n"
    "}\n";

// ─── TemplatePicker ──────────────────────────────────────────────────────────

TemplatePicker::TemplatePicker()
{
    m_templates = {
        { "Blank",              "Empty black canvas",                          kBlankSource },
        { "Gradient",           "Animated color cycling with wave pattern",    kGradientSource },
        { "Plasma",             "Classic sin/cos interference pattern",        kPlasmaSource },
        { "Cosmic Tunnel",      "Polar coordinate tunnel with scrolling",     kCosmicTunnelSource },
        { "Raymarching Sphere", "SDF sphere with directional lighting",       kRaymarchingSphereSource },
        { "Mandelbrot",         "Mandelbrot set with animated zoom",          kMandelbrotSource },
        { "Water Ripples",      "Animated concentric ripples",                kWaterRipplesSource },
        { "Starfield",          "Layered parallax starfield",                 kStarfieldSource },
        { "Magnetar Logo",      "Cel-shaded neutron star with accretion ring",     kMagnetarLogoSource },
        { "Feedback Blur (Multipass)", "Multipass ping-pong blur with moving dot", kFeedbackBlurSource },
    };
    fprintf(stderr, "[TemplatePicker] Initialized with %d templates\n",
            static_cast<int>(m_templates.size()));
}

void TemplatePicker::open()
{
    m_shouldOpen = true;
}

void TemplatePicker::render()
{
    if (m_shouldOpen) {
        ImGui::OpenPopup("New Shader Template");
        m_shouldOpen = false;
    }

    ImVec2 center = ImGui::GetMainViewport()->GetCenter();
    ImGui::SetNextWindowPos(center, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
    ImGui::SetNextWindowSize(ImVec2(500, 400), ImGuiCond_Appearing);

    if (ImGui::BeginPopupModal("New Shader Template", nullptr, ImGuiWindowFlags_NoResize)) {
        ImGui::Text("Choose a shader template:");
        ImGui::Separator();
        ImGui::Spacing();

        for (auto& tmpl : m_templates) {
            ImGui::PushID(tmpl.name);
            if (ImGui::Selectable("", false, 0, ImVec2(0, 40))) {
                m_selectedSource = tmpl.source;
                m_hasSelection = true;
                fprintf(stderr, "[TemplatePicker] Selected: %s\n", tmpl.name);
                ImGui::CloseCurrentPopup();
            }
            ImGui::SameLine();
            ImGui::BeginGroup();
            ImGui::TextUnformatted(tmpl.name);
            ImGui::TextDisabled("%s", tmpl.description);
            ImGui::EndGroup();
            ImGui::PopID();
        }

        ImGui::Spacing();
        ImGui::Separator();
        if (ImGui::Button("Cancel", ImVec2(120, 0))) {
            ImGui::CloseCurrentPopup();
        }
        ImGui::EndPopup();
    }
}

std::string TemplatePicker::takeSelection()
{
    m_hasSelection = false;
    return std::move(m_selectedSource);
}

} // namespace magnetar
